#spring.data.mongodb.uri=mongodb://mongouser:mongopassword@localhost:27017/product-service?authSource=admin
spring.mongodb.host=localhost
spring.mongodb.port=33333
spring.mongodb.database=product_spring
spring.mongodb.username=mongouser
spring.mongodb.password=mongopassword
spring.mongodb.authentication-database=admin

logging.level.root=INFO
logging.level.com.irfan=DEBUG

spring.jpa.show-sql=true